dom96/jester

jester.nim
readme.markdown

The PR provide a small update to clarify some of the inline documentation.
Previously, the comment for `PRequest.reqMeth` read as `Request method: HttpGet or HttpPost` which may be misunderstood as: request method can only be either `HttpGet` or `HttpPost`, and no other request methods are available.

Updated inline documentation for clarification

---

jester.nim

Fix name clash when importing `httpclient`.

use qualified name for Response

---

jester.nim
readme.markdown

Static files should be readable by “others.” If others are not allowed
to read the requested file, return a HTTP status 403 (“Forbidden”).
Is this okay or did I forget to add tests or an issue?

Check file permissions of static files

---

jester.nim

Turns out I've introduced this gcsafety issue some time ago.

Fixed gcsafety

---

jester.nim
tests/alltest.nim
tests/tester.nim

This replaces the method of adding return statements to the AST to break out of routes with a block and a break statement which works for templates and macros as well.

Fixing templates and macros for Jester

---

jester.nim

Removes the casting from `Time` to `int` which will break after https://github.com/nim-lang/Nim/pull/6978.

Remove bad cast in daysForward

---

jester.nim
jester/private/patterns.nim
jester/private/utils.nim

Hello Dominik. I am very pleased by jester and how simple the DSL it exposes is. I have straight-away started making internal use of it here at the lab to expose all sorts of neat things on the intranet. I am using jester with nim 0.17.2. From what I understand, stmt and expr may be replaced safely by typed and untyped. In addition, the immediate pragma appears to be going the way of history, and apparently it is just fine to use an untyped parameter to achieve the same effect. I've done a quick replacement of stmt/expr with typed/untyped, and removed immediate.
Please let me know if you would be okay with merging this. Thanks!

Replaced expr/stmt by untyped/typed and removed immediate pragma.

---

.gitignore

this gitignores all the non nim files under tests/ (but not deeper). Seems correct.

gitignore binaries generated by nimble test

---

changelog.markdown

https://localhost:5000/api/names was misleading

fix https links to http: jester doesnot serve https (yet)

---

jester.nim

DateTime was not converted to UTC before being marked as GMT in the cookie.  Also was missing a couple of cookie parameters such as domain and path -- which are necessary to make the cookie work.

Fix cookie datetime conversion and missing parameters [bugfix]

---

readme.markdown

Remove out of date note that devel Nim compiler is required.

Remove notice about requiring devel nim

---

jester.nim

header tuple should be `tuple[key, val: string]` because difinition of header in `newHttpHeaders` is `tuple[key, val: string]`  
[proc newHttpHeaders](https://nim-lang.org/docs/httpcore.html#newHttpHeaders%2CopenArray%5Btuple%5Bstring%2Cstring%5D%5D)
Especially, when using `after`, error is happened
```nim
routes:
after re"/api.*":
var headers = result[2].get # tuple[key, val: string]
headers.add(("key", "val"))
resp result[1], headers, result[3] # error railed becase expected header is tuple[key, value: string]
```

rename header value as val

---

jester.nim
jester/request.nim

This fixes the "Bad file descriptor" error when running asynchttpserver behind an nginx instance. There might be some more serious underlying issue causing this, but for now I see it as Jester using asynchttpserver incorrectly which is fixed in this pr. Tested with both asynchttpserver and httpbeast.

Use async to fix asynchttpserver

---

jester.nim

I was running jester on windows and couldn't get static files to be served without incurring a 400 bad request. After digging around the source I found that the comparison on line 318 of the original source `if pathDir.startsWith(staticDir)` would return false because of a trailing slash.
Example:
`pathDir = "%somepath%/client/build"`
`staticDir = "%somepath%/client/build/"`
After changing the way the pathDir prevents directory traversal and ensuring that the staticDir is always without a trailing slash, it works on windows.
I wanted to test using `nimble test` but unfortunately they are unable to run due to a combination of out of date async libraries `PCustomOverlap -> CustomRef` and the inability to run the asyncdispatcher server which I didn't look into.
I was hoping you could review …

fixed paths for staticDir on windows which returned 400 bad request.

---

changelog.markdown
jester.nim
tests/alltest.nim
tests/tester.nim

Fixes #264
It makes more sense (to me) for halting to be the default behavior when redirecting.  But if you'd rather halt default to false to be completely backward compatible, I can change it.
Sorry for the slew of issues and PRs ;) I'm not expecting you to rush through them

Add halt option to redirect; default to halting

---

jester.nim
jester/private/utils.nim

This PR adds a new setting to specify the number threads when compiled with `useHttpBeast`.
Solves #233 and allows the user to define the number of threads `httpBeast` may use when it is initiated from within `jester`.
**Example**
```nim
import jester
settings:
bindAddr    = "127.0.0.1"
port        = Port(5040)
numThreads  = 3
routes:
get "/":
resp "threads"
```
```bash
$ nim c -r specify_threads.nim
INFO Jester is making jokes at http://127.0.0.1:5040
Starting 3 threads
Listening on port 5040
```

Specify number of threads to be used by httpbeast

---

jester.nim

I had to write some pretty painful code to set a header before a redirect. 1 character change so no tests

Make setHeader public

---

changelog.markdown
jester.nim
tests/customRouter.nim
tests/issue296.nim
tests/tester.nim

Fixes #269 (includes #267 because it relies on the testing changes included there)
`nimble test` doesn't work for me because of some of the other dependencies failing (as noted in #263), but I've tested the change and seen the added test pass.

Fix error handler redirecting

---

jester.nim
tests/alltest.nim
tests/tester.nim

Supersedes #294 with the minimal change needed to accomplish the fix.

Allow setHeader and resp with headers to be used in the same handler

---

jester.nim
jester/private/utils.nim

Right now, Jester can't handle a post body larger than 8MB if [asynchttpserver](https://nim-lang.org/docs/asynchttpserver.html) is used.
This is a configurable setting (`maxBody`) in newAsyncHttpServer, yet it is not currently exposed in the settings object. This PR adds `maxBody` to the settings object and passes it on to newAsyncHttpServer when serve is called.
The default value ( 8388608 ) is directly taken from the asynchttpserver docs.

Expose asynchttpserver maxBody setting

---

changelog.markdown
jester.nim
jester/request.nim

This fixes issue https://github.com/dom96/jester/issues/312.
**Base**
_Request to roll back commit https://github.com/dom96/jester/commit/a03b5be0b72f1a686b6ca594c145cee665e6db7b which implemented PR https://github.com/dom96/jester/pull/171 which fixed Issue https://github.com/dom96/jester/issues/159._
**Description**
Instead of a rollback of the previous commit, since that solves some problems, this commit fixes the bug which was introduces for non-URL params. We were already decoding non-URL parameters, the previous commit implemented a "double decode".
To fix this we now just decode all params on init. It adds a little overhead, but using `benchy` it doesn't look that bad.

Decode all URL params no matter what

---

jester.nim

This PR exposes the numThreads parameter in router settings, so you don't need to separately set the numThreads property of Settings object after creation:
```
let settings = newSettings(numThreads = 16)
```
instead of
```
let settings = newSettings()
settings.numThreads = 16
```

Expose numThreads in newSettings proc

---

readme.markdown

Seems like some field types in the Request object were changed in the code but not in the README.

Updated README Request type
