jester.nim

This will reduce bytes over the wire for repeat visitors, even if it doesn't reduce the number of round trips

Add ETags to static content

---

jester.nim

1. This is more elegant solution and can be overridden by the jester user.
2. We express explicitly what is an error, a warning or info.
3. We can customize logging or disable it at all for performance reasons.
4. If logging has no handler specified, the console one is added with lvlInfo
for debug builds and lvlWarn for release builds.

Use logging module instead echo

---

jester.nim

add "charset=utf-8" to Content-Type

add "charset=utf-8" to Content-Type

---

jester.nim

Fixed serving static with percent-escaped uri

---

jester.nim

Noticed that issue was solved by @shawnye

`attachment` failed to reply fix

---

jester.nim
tests/alltest.nim

PATCH:  https://tools.ietf.org/html/rfc5789
Needed for issue #57

Added HTTP PATCH support

---

private/utils.nim

Preserve MultipartData order

---

jester.nim

1. Don't crash when exception msg is nil.
2. Log the error.

Better error handling

---

readme.markdown

remove HTTP methods limitation in readme

---

jester.nim

This allows to customize response in case of exception.

Custom error filter support

---

jester.nim

It is passed down to newAsyncHttpServer to enable SO_REUSEPORT
Disabled by default.

Add reusePort setting

---

jester.nim
jester/private/utils.nim
readme.markdown
tests/example2.nim

some code are unused and deprecated

readme  and fix deprecated

---

jester.nim

Add a resp() that serializes  the response and set the appropriate content-type.

Add JSON resp

---

jester/request.nim

Allow url params:
https://github.com/dom96/httpbeast/issues/4
https://github.com/dom96/jester/issues/146
**Test code**
```nim
import jester, asyncdispatch
routes:
get "/projects/all":
if @"username" == "nimmer":
resp("OK")
else:
resp("No access")
get "/projects/@projectid":
if @"projectid" == "1": 
resp("You have access")
else:
resp("No access")
get "/":
resp("Hello World")
```

Remove ? from base url

---

jester.nim

Also fixed the parameter styling to be consistent.

jester: add Domain, Path support to setCookie

---

jester.nim

As mentioned in https://forum.nim-lang.org/t/5084#31955

Add client socket connection close

---

jester/private/errorpages.nim

I tend to think that if a proc has no side-effects, we can add value and safety by making it a func. Sound sensible?

Errorpages can (should?) be func

---

jester.nim

This change allows me to write cookie-setting code outside of a jester handler.  Like this:
```nim
proc signout*(request: Request, responseHeaders: var ResponseHeaders) =
let cookie = request.cookies.getOrDefault(SESSIONCOOKIE)
delete_session(cookie)
responseHeaders.setCookie(SESSIONCOOKIE, "", secure = not DEVMODE, path="/")
router myrouter:  
get "/auth/logout":
signout(request, responseHeaders)
redirect "/"
```
I'm interested to know if this is the best approach or what you would change.  For instance, is it too much to make the `ResponseHeaders` type?
Thanks for making Jester!

Add responseHeaders template to allow for setting cookies outside of handlers

---

jester/private/utils.nim

https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure

Explicitly add SameSite=None cookie

---

jester/request.nim
readme.markdown
tests/alltest.nim
tests/tester.nim

Added query proc to get query string of request

---

jester.nim
jester.nimble

https://github.com/dom96/jester/issues/314
Is a new tag required? Then it might be possible to delete existing tag and create a new one in Github.

Update jester.nimble and jester.nim to 0.6.0
